Repository drftpd-ng/drftpd, pull requests merged in 2023-10, with the labels that each got.

#281 Fix building slave not overwriting resource files in output directory
  src/core/slave/pom.xml
Labels: bug

#283 Replace passcrypt hard coded values with constants
  src/core/master/src/main/java/org/drftpd/master/usermanager/encryptedjavabeans/EncryptedBeanUser.java
  src/core/master/src/main/java/org/drftpd/master/usermanager/encryptedjavabeans/EncryptedBeanUserManager.java
Labels: enhancement

#284 Improve sitebot logging to include the exception message
  src/plugins/sitebot/src/main/java/org/drftpd/master/sitebot/SiteBot.java
Labels: enhancement

#285 Update dependencies to latest api compatible versions
  pom.xml
  src/core/common/pom.xml
  src/core/master/pom.xml
  src/core/slave/pom.xml
  src/plugins/speedtest-net/speedtest-net-slave/pom.xml
Labels: dependencies

#286 Re-introduce remerge depth and more logging
  src/core/master/src/main/java/org/drftpd/master/slavemanagement/RemoteSlave.java
  src/core/master/src/main/java/org/drftpd/master/vfs/DirectoryHandle.java
  src/core/master/src/main/java/org/drftpd/master/vfs/FileHandle.java
  src/core/master/src/main/java/org/drftpd/master/vfs/InodeHandle.java
  src/core/master/src/main/java/org/drftpd/master/vfs/LinkHandle.java
  src/core/master/src/main/java/org/drftpd/master/vfs/VirtualFileSystemFile.java
  src/core/slave/src/main/java/org/drftpd/slave/Slave.java
  src/core/slave/src/main/java/org/drftpd/slave/network/AsyncResponseRemerge.java
  src/core/slave/src/main/java/org/drftpd/slave/protocol/BasicHandler.java
  src/core/slave/src/main/java/org/drftpd/slave/vfs/RootCollection.java
Labels: bug
